### ISSUE TITLE
Code Introduced in dc42b41 breaks Visual Studio compilation

### ISSUE THREAD

**Issue by tuldok89** [mapeditor/tiled#98]
The code that was added in automapper.cpp in rev. dc42b41 makes Visual Studio choke with the following error message:

```
..\..\..\src\tiled\automapper.cpp(521) : error C2057: expected constant expression
..\..\..\src\tiled\automapper.cpp(521) : error C2466: cannot allocate an array of constant size 0
..\..\..\src\tiled\automapper.cpp(521) : error C2133: 'ruleRegionInLayer' : unknown size
```
